import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  styles  from "@/app/page.module.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import BlogList from "@/components/BlogList";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header className={styles.header}/>
        <BlogList className={styles.sidebar}/>
        {children}
        <Footer className={styles.footer}/> 
      </body>
    </html>
  );
}
